version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8000
        - VITE_AI_SERVICE_URL=http://ai-service:5001
        - VITE_DB_SERVICE_URL=http://localhost:5000
    ports:
      - "3000:5173"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/socialdb
      - AI_SERVICE_URL=http://ai-service:5001
    container_name: backend
    networks:
      - app-network
    depends_on:
      - ai-service
    ports:
      - "8000:8000"

  ai-service:
    build: ./ai_service
    ports:
      - "5001:5001"
    environment:
      - MODEL_NAME=gemma3:1b
      - OLLAMA_HOST=http://ollama:11434
      - GOOGLE_API_KEY=AIzaSyA5mCaRs4w6H2V2eZwJ_fWw4-d6ueOTD9g
    networks:
      - app-network
    depends_on:
      - ollama

  ollama:
    build: ./ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network
  
  worker:
    build: ./worker
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://atharvkharat68_db_user:hvccPYMgLuo8l6H5@cluster0.dbpu8k9.mongodb.net/socialdb?retryWrites=true&w=majority
    networks:
      - app-network


volumes:
  mongodata:
  ollama_data:

networks:
  app-network:
    driver: bridge
